---
title: "Topics In Statistics - Smart Data"
subtitle: "A good start with some mathematics and statistics refreshers"
format: html
toc: true
date: last-modified
date-format: "[Last Updated on] MMM D, YYYY"
execute: 
  freeze: auto
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
library(tidyverse)
```

This refresher course is intended to help you brush up on essential linear algebra tools and some key statistical concepts.


**Course Overview**

This course is specifically tailored for those who are stepping into data science, it is intended to present or refresh two key tools in Data Science : Principal Component Analysis (PCA) and Regression analysis. These two mathematical conepts in Data science are built on basic Linear algebra ideas. While not designed as a math course, this course will provide crucial reminders of linear algebra indispensable for statistics and how they are used in PCA and Regression.  We will also have labs to use this method on practical example.


**What You Will Learn**

1. **Linear Surival Kit**:
   - Vectors and matrices: Definitions, operations, and properties
   - Systems of linear equations
   - Matrix decomposition and eigenvalues

2. **Principal Component Analysis (PCA)**:
   - Understanding the concept and purpose of PCA
   - Steps involved in performing PCA
   - Applications of PCA in data reduction and visualization

3. **Linear Regression**:
   - Introduction to regression analysis
   - Building and interpreting multiple regression models
   - Evaluating model performance


**Course Format**

This course is conducted in English and combines lectures, practical examples, and hands-on exercises to reinforce learning. Whether you're a beginner or someone looking to refresh these topics, the structured approach and close link made between the linear algebra concept and their use in statistics  will help you grasp and apply these concepts effectively.


**How to use this website**

You can find the lecture notes on the top menu on the right, as well as the Rmarkdown and/or Jupyter notebook used during the labs. The website will be updated during the course.


Please, if you have any remarks regarding the material on this website (typos, lack of clarity or anything else) please contact me.

Enjoy!

