---
title: "References"
format: html
toc: true
date: last-modified
date-format: "[Last Updated on] MMMM, YYYY"
execute: 
  freeze: auto
---




```{r setup, include=FALSE, eval = TRUE}
with_sol <- TRUE ## in order to control the output
with_course <- TRUE
library(RefManageR)
library(tidyverse)
```

```{r xaringanExtra-share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

```{r reference,  include=FALSE, cache=FALSE, eval = TRUE}
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           cite.style = "alphabetic",
           style = "markdown",
           hyperlink = FALSE,
           dashed = FALSE)
myBib <- ReadBib("./topics.bib", check = FALSE)
```

::: {.hidden}

```{r}
liste <- 
  readLines('topics.bib') |> 
  as_tibble() |> 
  filter(stringr::str_detect(value, pattern = '@')) |> 
  mutate(key = stringr::str_remove(value, pattern = '@[:alnum:]+\\{')) |> 
  mutate(key = stringr::str_remove(key, pattern = ',')) |> 
  pull()
  
NoCite(bib = myBib, liste)

```

:::


```{r refs, echo=FALSE, results="asis", eval = TRUE, cache = FALSE}
PrintBibliography(myBib)
```

```{r ggplot_back, echo = FALSE, eval = TRUE}
ggplot <- function(...) ggplot2::ggplot(...) 
```



