---
title: Linear Regression
author: Marie-Pierre Etienne
date: '2024/07/24 (updated: `r Sys.Date()`)'
institute: https://marieetienne.github.io/TopicsInStatistics/
csl: ../courses_tools/resources/apa-no-doi-no-issue.csl
output:
  xaringan::moon_reader:
    css: [  'metropolis',  'mpe_pres.css']
    lib_dir: libs
    nature:
      ratio: 16:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      beforeInit: '../courses_tools/resources/collapseoutput.js'
    includes:
      after_body: '../courses_tools/resources/insert-logo.html'
fontsize: 11pt
params:
  child_path: ''
execute: 
  freeze: auto
---



```{r setup, include=FALSE, eval = TRUE}
with_sol <- TRUE ## in order to control the output
with_course <- TRUE
library(RefManageR)
library(tidyverse)
```

```{r xaringanExtra-share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

```{r reference,  include=FALSE, cache=FALSE, eval = TRUE}
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           cite.style = "alphabetic",
           style = "markdown",
           hyperlink = FALSE,
           dashed = FALSE)
myBib <- ReadBib("./topics.bib", check = FALSE)
```


---

```{r ggplot_back, echo = FALSE, eval = TRUE}
ggplot <- function(...) ggplot2::ggplot(...) 
```



